<?php


namespace Packages\Country\tests\Feature;


use Illuminate\Foundation\Testing\DatabaseMigrations;
use Livewire\Livewire;
use Packages\Country\App\Http\Controllers\Livewire\country\Table;
use Packages\Country\App\Models\Country;
use Tests\Feature\cms\CmsTestCase;

class CountryTest extends CmsTestCase {

    use DatabaseMigrations;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->actingAs($this->user_with_permissions);
    }


    /** @test */
    public function a_authorized_user_can_see_the_link_to_the_countries_module()
    {
        $this->get(route('cms.home'))->assertStatus(200)->assertSee(route('cms.country.index'));
    }

    /** @test */
    public function a_user_without_permissions_can_see_the_link_to_the_countries_module()
    {
        $this->actingAs($this->user_without_permissions);
        $this->get(route('cms.home'))->assertStatus(200)->assertDontSee(route('cms.country.index'));
    }

    /** @test */
    public function a_authorized_user_can_access_to_the_index_page()
    {
        $this->withoutExceptionHandling();
        $this->get(route('cms.country.index'))
            ->assertStatus(200)
            ->assertSee(__('country::cms.list_countries'))
            ->assertSeeLivewire('cms.country.table');
    }

    /** @test */
    public function a_unauthorized_user_cant_acess_to_the_index_page()
    {
        $this->actingAs($this->user_without_permissions);
        $this->get(route('cms.country.index'))
            ->assertStatus(403);
    }

    /** @test */
    public function a_authorized_user_can_see_the_countries()
    {
        $countries = Country::orderByTranslation('name', 'asc')->limit(20)->get();
        $livewire = Livewire::test(Table::class);
        foreach($countries as $country)
        {
            $livewire->assertSee($country->code);
            $livewire->assertSee($country->flag_image);
        }
    }

    /** @test */
    public function a_authorized_user_can_see_the_link_to_the_list_of_regions_and_taxes()
    {
        $countries = Country::orderByTranslation('name', 'asc')->limit(20)->get();
        $livewire = Livewire::test(Table::class);
        foreach($countries as $country)
        {
            $livewire->assertSeeHtml(route('cms.country.region.index', ['country'=>$country->id]));
            $livewire->assertSeeLivewire('cms.tax.widget');
        }
    }



    protected function getPermissions()
    {
        return ['country_index', 'country_store', 'country_update', 'country_destroy'];
    }
}
