<?php


namespace Packages\Country\tests\Feature;


use Livewire\Livewire;
use Packages\Country\App\Http\Controllers\Livewire\region\Table;
use Packages\Country\App\Models\Country;
use PHPUnit\Framework\Constraint\Count;
use Tests\Feature\cms\CmsTestCase;

class RegionTest extends CmsTestCase {

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->actingAs($this->user_with_permissions);
    }

    /** @test */
    public function a_authorized_user_can_access_to_the_list_of_regions_for_a_given_country()
    {
        $country = Country::first();

        $response = $this->get(route('cms.country.region.index', ['country'=>$country->id]));

        $response->assertStatus(200);
        $response->assertSee($country->name);
        $response->assertSeeLivewire('cms.region.table');
    }

    /** @test */
    public function a_authorized_user_can_see_the_list_of_regions_for_a_given_country()
    {
        $country = Country::first();

        $live = Livewire::test(Table::class, ['country'=>$country]);

        foreach($country->regions()->orderBy('name', 'asc')->limit(10)->get() as $region)
        {
            $live->assertSee($region->name);
        }

    }

    /** @test */
    public function a_user_can_get_the_regions_filtered_by_country()
    {
        $country = Country::where('code', 'pt')->first();
        $expected_results = $country->regions()->orderBy('name', 'asc')->get();

        $response = $this->get(route('regions.get_by_country', ['country'=>$country->id]));

        $response->assertStatus(200);
        $this->assertEquals($expected_results, $response->baseResponse->original);
    }





    protected function getPermissions()
    {
        return ['country_index', 'country_store', 'country_update', 'country_destroy'];
    }
}
