<?php


namespace Packages\Country\tests\Feature;


use Illuminate\Foundation\Testing\DatabaseMigrations;
use Livewire\Livewire;
use Packages\Country\App\Http\Controllers\Livewire\tax\TaxWidget;
use Packages\Country\App\Models\Country;
use Tests\Feature\cms\CmsTestCase;

class TaxTest extends CmsTestCase {

    use DatabaseMigrations;


    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->actingAs($this->user_with_permissions);
    }


    /** @test */
    public function a_user_without_permissions_cant_mount_the_tax_widget()
    {
        $this->actingAs($this->user_without_permissions);
        Livewire::test(TaxWidget::class, ['taxable'=>Country::first()])->assertSee('');

    }
    /** @test */
    public function a_user_with_permissions_can_mount_the_tax_widget()
    {
        Livewire::test(TaxWidget::class, ['taxable'=>Country::first()])->assertSee(__('country::cms.edit_default_tax'));
    }

    /** @test */
    public function a_user_wiht_permissions_can_update_a_tax_for_a_given_taxable()
    {
        $country = Country::first();
        $live = Livewire::test(TaxWidget::class, ['taxable'=>$country]);
        $live->set('tax', 3);
        $live->call('saveTax');
        $this->assertEquals(3, $country->taxes->first()->percentage);
    }

    /** @test */
    public function a_tax_is_required()
    {
        $country = Country::first();
        $live = Livewire::test(TaxWidget::class, ['taxable'=>$country]);
        $live->set('tax', '');
        $live->assertHasErrors(['tax' => 'required']);
    }

    /** @test */
    public function a_tax_must_be_numeric()
    {
        $country = Country::first();
        $live = Livewire::test(TaxWidget::class, ['taxable'=>$country]);
        $live->set('tax', 're');
        $live->assertHasErrors(['tax' => 'numeric']);
    }



    protected function getPermissions()
    {
        return ['tax_index', 'tax_store', 'tax_update', 'tax_destroy'];
    }
}
