<?php

namespace Packages\Country\tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Livewire\Livewire;
use Packages\Country\App\Http\Controllers\Livewire\zoneables\AddItems;
use Packages\Country\App\Http\Controllers\Livewire\zoneables\Table;
use Packages\Country\App\Models\Country;
use Packages\Country\App\Models\Zone;
use PHPUnit\Framework\Constraint\Count;
use Tests\Feature\cms\CmsTestCase;

class ZoneablesTest extends CmsTestCase {

    use DatabaseMigrations;

    public $zone;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->actingAs($this->user_with_permissions);
        $this->zone = Zone::factory()->create();
        $this->zone->countries()->attach(Country::orderBy('name', 'asc')->limit(5)->get());
    }

    /** @test */
    public function a_authorized_user_can_access_to_the_list_of_zoneables()
    {
        $response = $this->get(route('cms.zoneables.index', ['zone'=>$this->zone->id]));

        $response->assertStatus(200);
        $response->assertSee(__('country::cms.list_zoneables'));
    }

    /** @test */
    public function a_authorized_user_can_see_the_link_to_add_new_zoneables()
    {
        $response = $this->get(route('cms.zoneables.index', ['zone'=>$this->zone->id]));

        $response->assertStatus(200);
        $response->assertSee(route('cms.zoneables.edit', ['zone'=>$this->zone->id]));
    }

    /** @test */
    public function a_authorized_user_can_see_list_of_countries_attached_to_a_given_zone()
    {
        $livewire = Livewire::test(Table::class, ['zone'=>$this->zone]);

        $this->zone->countries->each(function($country) use ($livewire){
           $livewire->assertSee($country->name);
        });
    }

    /** @test */
    public function a_authorized_user_can_remove_a_country_from_a_given_zone()
    {
        $livewire = Livewire::test(Table::class, ['zone'=>$this->zone]);

        $livewire->call('remove', ['country'=>$this->zone->countries->first()->id]);

        $this->assertCount(4, $this->zone->fresh()->countries);
    }

    /** @test */
    public function a_authorized_user_can_acess_to_the_page_to_add_countries()
    {
        $response = $this->get(route('cms.zoneables.edit', ['zone'=>$this->zone->id]));

        $response->assertStatus(200);
        $response->assertSee(__('country::cms.add_zoneables'));
    }

    /** @test */
    public function the_livewire_component_to_add_zoneables_dont_show_attached_zoneables()
    {
        $livewire = Livewire::test(AddItems::class, ['zone'=>$this->zone->id]);

        $countries = Country::orderBy('name', 'asc')->limit(5)->get()->each(function($country)use($livewire){
            $livewire->assertDontSee($country->name);
        });
    }

    /** @test */
    public function a_user_can_attach_a_new_country_to_the_zone()
    {
        $livewire = Livewire::test(AddItems::class, ['zone'=>$this->zone->id]);

        $country_to_add = Country::where('code', 'pt')->first();
        $livewire->call('add', $country_to_add->id);

        $this->assertCount(6, $this->zone->fresh()->countries);
        $this->assertNotEmpty($this->zone->fresh()->countries->where('id', $country_to_add->id)->first());

    }


    protected function getPermissions()
    {
        return ['country_index'];
    }
}
