<?php

namespace Packages\Country\tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Livewire\Livewire;
use Packages\Country\App\Http\Controllers\Livewire\zones\Table;
use Packages\Country\App\Models\Zone;
use Tests\Feature\cms\CmsTestCase;

class ZonesTest extends CmsTestCase {

    use DatabaseMigrations;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->actingAs($this->user_with_permissions);
    }

    /** @test */
    public function a_authorized_user_can_see_the_link_to_see_the_list_of_countries()
    {
        $response = $this->get(route('cms.country.index'));

        $response->assertStatus(200)->assertSee(route('cms.zones.index'));
    }

    /** @test */
    public function a_authorized_user_can_access_to_the_list_of_countries()
    {
        $response = $this->get(route('cms.zones.index'));

        $response->assertStatus(200);
        $response->assertSee(__('country::cms.list_zones'));
        $response->assertSee(route('cms.zones.create'));
    }

    /** @test */
    public function a_authorized_user_can_see_the_form_to_create_new_zones()
    {
        $response = $this->get(route('cms.zones.create'));

        $response->assertStatus(200);
        $response->assertSee(route('cms.zones.store'));
    }

    /** @test */
    public function a_authorized_user_can_create_a_new_zone()
    {
        $data = ['name'=>'Zone 1'];

        $response = $this->post(route('cms.zones.store', $data));

        $response->assertStatus(302);
        $this->assertDatabaseHas('zones', $data);
    }

    /** test */
    public function a_authorized_user_can_acess_to_the_edion_form()
    {
        $data = ['name'=>'Zone 1'];
        $zone = Zone::factory()->create($data);

        $response = $this->get(route('cms.zones.edit', ['zone'=>$zone->id]));

        $response->assertStatus(200);
        $response->assertSee($data['name']);
        $response->assertSee(route('cms.zones.update', ['zone'=>$zone->id]));
    }

    /** @test */
    public function a_authrized_user_can_update_a_zone()
    {
        $data = ['name'=>'Zone 1'];
        $zone = Zone::factory()->create($data);
        $new_data = ['name'=>'Main zone'];

        $response = $this->patch(route('cms.zones.update', ['zone'=>$zone->id]), $new_data);

        $response->assertStatus(302);
        $response->assertRedirect(route('cms.zones.index'));

        //$this->assertDatabaseHas('zones', $new_data);
        //$this->assertDatabaseMissing('zones', $data);
    }

    /** @test */
    public function a_authorized_user_can_see_the_list_of_zones()
    {
        $zones = Zone::factory(4)->create();

        $livewire = Livewire::test(Table::class);

        $zones->each(function($item) use ($livewire) {
            $livewire->assertSee($item->name)
                    ->assertSee(route('cms.zones.edit', ['zone'=>$item->id]));
        });
    }

    /** @test */
    public function a_authorized_user_can_delete_a_zone()
    {
        $zone = Zone::factory()->create();

        $livewire = Livewire::test(Table::class);
        $livewire->call('delete', $zone->id);

        $this->assertDatabaseMissing('zones', ['name'=>$zone->name]);
    }

    /** @test */
    public function a_authorized_user_can_see_the_link_to_add_countries_for_a_given_zone()
    {
        $zone = Zone::factory()->create();
        $livewire = Livewire::test(Table::class);
        $livewire->assertSee(route('cms.zoneables.index', ['zone'=>$zone->id]));
    }

    protected function getPermissions()
    {
        return ['country_index'];
    }
}
